// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '@/lib/logger';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Adicionar logs de requisições em desenvolvimento
  global: {
    headers: {
      'X-Client-Info': 'konnecta-aidc',
    },
  },
});

// Interceptar requisições para logging
if (import.meta.env.DEV) {
  // Log de inicialização
  logger.info('SUPABASE', `Cliente inicializado - URL: ${SUPABASE_URL?.substring(0, 30)}...`);

  // Monitorar mudanças de autenticação
  supabase.auth.onAuthStateChange((event, session) => {
    logger.auth(`Auth state changed: ${event}`, {
      userId: session?.user?.id,
      email: session?.user?.email,
    });
  });
}